# This rule is not used by the project liqo-security-engine itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over security.liqo.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: liqo-security-engine
    app.kubernetes.io/managed-by: kustomize
  name: peeringconnectivity-admin-role
rules:
- apiGroups:
  - security.liqo.io
  resources:
  - peeringconnectivities
  verbs:
  - '*'
- apiGroups:
  - security.liqo.io
  resources:
  - peeringconnectivities/status
  verbs:
  - get
