# This rule is not used by the project liqo-security-engine itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to security.liqo.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: liqo-security-engine
    app.kubernetes.io/managed-by: kustomize
  name: peeringsecurity-viewer-role
rules:
- apiGroups:
  - security.liqo.io
  resources:
  - peeringsecurities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.liqo.io
  resources:
  - peeringsecurities/status
  verbs:
  - get
