apiVersion: connectivity.liqo.io/v1
kind: PeeringConnectivity
metadata:
  labels:
    app.kubernetes.io/name: liqo-connectivity-engine
    app.kubernetes.io/managed-by: kustomize
  name: peeringconnectivity-sample
spec:
  # TODO(user): Add fields here
