apiVersion: security.liqo.io/v1
kind: PeeringSecurity
metadata:
  labels:
    app.kubernetes.io/name: liqo-security-engine
    app.kubernetes.io/managed-by: kustomize
  name: peeringsecurity-sample
spec:
  # TODO(user): Add fields here
